In [1]:
import numpy as np

In [2]:
narr = np.array([1,2,3,4,5])
narr

array([1, 2, 3, 4, 5])

In [4]:
arr_2d = [[1,2,3], [4,5,6],[7,8,9]]
narr_2d = np.array(arr_2d)
narr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(10)
np.arange(35,45,2)

array([35, 37, 39, 41, 43])

In [10]:
np.zeros(5)
np.zeros((3,4))
np.zeros((3,4,5))
np.zeros((2,3,4,5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [14]:
np.ones(4)
np.ones((2,2))
np.ones((2,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [18]:
np.linspace(1,10,5)
np.linspace(1,5,5)
np.linspace(start=45, stop=100, num=30)
arr = np.linspace(start=45, stop=100, num=30)
arr.dtype

dtype('float64')

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
np.random.rand()
np.random.rand(3)
np.random.rand(3,4)
np.random.rand(23,3,4)
np.random.rand(3,4)
np.random.randint(1,100,size=5)
np.random.randint(20,50,size=(2,3))
np.random.randint(20,50,size=(3,2,3))

array([[[32, 42, 27],
        [34, 25, 49]],

       [[21, 33, 35],
        [20, 41, 47]],

       [[24, 27, 20],
        [26, 26, 24]]], dtype=int32)

In [30]:
rarr = np.random.randint(20,50,size=(3,2,3))

In [31]:
rarr.shape

(3, 2, 3)

In [33]:
rarr.reshape(2,9)
rarr.reshape(3,3,2)

array([[[49, 45],
        [45, 46],
        [39, 20]],

       [[34, 48],
        [38, 46],
        [29, 20]],

       [[41, 39],
        [34, 46],
        [47, 21]]], dtype=int32)

In [34]:
arr =  np.random.randint(1,100,size=30)

In [41]:
arr.max()
arr.argmax()
arr.min()
arr.argmin()

np.int64(11)

In [42]:
# indexing

In [43]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
arr[5]
arr[-1]

np.int64(10)

In [51]:
arr[0:5]
arr[:3]
arr[0:3:1]
arr[5:]
arr[:8]
arr[:8:2]

array([0, 2, 4, 6])

In [52]:
arr2 = arr[1:7]
arr2

array([1, 2, 3, 4, 5, 6])

In [53]:
arr2[2:]

array([3, 4, 5, 6])

In [54]:
arr2[2]=99

In [55]:
arr2

array([ 1,  2, 99,  4,  5,  6])

In [56]:
arr

array([ 0,  1,  2, 99,  4,  5,  6,  7,  8,  9, 10])

In [58]:
main_arr = np.arange(20)
sliced_array = main_arr[3:13]

In [60]:
sliced_array[:] = -11

In [61]:
sliced_array

array([-11, -11, -11, -11, -11, -11, -11, -11, -11, -11])

In [65]:
main_arr = np.arange(10)
copied_slice = main_arr[4:9].copy() 
copied_slice[:] = 99 
copied_slice
main_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
# matrix_indexing 

In [68]:
matrix = np.array([[1,2,3], [4,5,6]])
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
matrix[0][1]
matrix[0,1]

np.int64(2)

In [71]:
mat_python = [[1,2,3], [4,5,6]] 
mat_python

[[1, 2, 3], [4, 5, 6]]

In [83]:
slice = mat_python[1:]

In [84]:
slice

[[4, 5, 6]]

In [85]:
slice2 = [arr[1:] for arr in slice]

In [86]:
slice2

[[5, 6]]

In [87]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
matrix[1:3, 1:3]

array([[5, 6]])

In [91]:
matrix[1:]
matrix[:,1:]

array([[2, 3],
       [5, 6]])

In [92]:
# conditional

In [93]:
arr = np.random.randint(1,101,size=16)

In [94]:
arr>25

array([ True,  True,  True,  True, False, False, False, False, False,
        True, False,  True,  True,  True,  True,  True])

In [95]:
arr[0]

np.int32(71)

In [96]:
boolean_array = arr>25

In [97]:
arr[boolean_array]

array([71, 64, 53, 70, 88, 64, 54, 43, 97, 73], dtype=int32)

In [98]:
arr[arr>25]

array([71, 64, 53, 70, 88, 64, 54, 43, 97, 73], dtype=int32)

In [99]:
# numpy operations

In [100]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [105]:
arr + arr
arr+100
arr-1
arr*2
arr/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [106]:
# universal function

In [110]:
np.max(arr)
arr.max()
arr.argmax()
arr.min()
arr.argmin()

np.int64(0)

In [118]:
np.shape(arr)
np.sum(arr)
np.mean(arr)
np.std(arr)
np.exp(arr)
np.square(arr)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [119]:
# 11-8-2025

In [120]:
arr = np.arange(16)

In [121]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [130]:
arr[0]
arr[-2]
arr[2:7]
arr[:]
arr[:11]
arr[10:-1]
arr[::1]
arr[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [136]:
parr = [1,2,3,4,5,6,7,8,9]
sliced = parr[0:3]

In [137]:
sliced[1] = 100

In [138]:
sliced

[1, 100, 3]

In [139]:
parr

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [140]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [145]:
npsliced = arr[1:5]

In [146]:
npsliced[:] = 99

In [147]:
npsliced

array([99, 99, 99, 99])

In [150]:
arr

array([ 0, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [151]:
sliced_copy = arr[6:12].copy()

In [154]:
sliced_copy[:] = 999

In [155]:
sliced_copy

array([999, 999, 999, 999, 999, 999])

In [156]:
arr

array([ 0, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [161]:
scaler = 50
vector = [1,2,3]
matrix = np.array([[1,2,3], [4,5,6]])
tensor = [matrix, matrix]

In [162]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [163]:
tensor

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2, 3],
        [4, 5, 6]])]

In [174]:
matrix[1][0]
matrix[1,0]
matrix[1:2,1:3]
matrix[:, 0:2]
matrix[:, :3]
matrix[:3, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [166]:
py2d = [[1,2,3], [100,200,300]]

In [168]:
py2d[0][1:]

[2, 3]

In [170]:
ans = []
for  i in [1,2,3]: 
    print(i)

1
2
3


In [175]:
rarr = np.random.randn(5,5)
rarr

array([[ 0.54251892,  0.15693258, -0.49860663,  0.72297843, -1.2510211 ],
       [-1.81107423, -0.09619444, -1.23986438, -0.57163421,  0.36012346],
       [ 0.4101673 , -0.5482916 , -0.75213823, -2.13182069,  1.73681786],
       [-0.05513463, -0.97691228,  0.61070724, -0.34332685, -0.28627222],
       [ 0.18883192, -1.2948039 , -0.38196877, -0.63377978,  1.38460681]])

In [177]:
rarr[1:3, 1:3]

array([[-0.09619444, -1.23986438],
       [-0.5482916 , -0.75213823]])