In [2]:
import numpy as np

In [2]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
a2 = np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
a3 = np.array([[[1,2,3],[4,5,6]], [[0,0,0],[-1,-1,-1]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 0,  0,  0],
        [-1, -1, -1]]])

In [10]:
print(a1.shape)
print(a2.shape)
print(a3.shape)

(3,)
(2, 3)
(2, 2, 3)


In [11]:
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [12]:
print(len(a1))
print(len(a2))
print(len(a3))

3
2
2


In [13]:
print(a1.size)
print(a2.size)
print(a3.size)

3
6
12


In [14]:
print(a1.dtype)

int64


In [15]:
a1.astype('float')

array([1., 2., 3.])

In [16]:
a1.tolist()

[1, 2, 3]

In [22]:
# initial placeholder 
np.zeros((3,4))
np.ones((2,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [25]:
np.arange(10,25,5)
np.arange(10,26,5)

array([10, 15, 20, 25])

In [26]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [29]:
lst = np.logspace(1,3,5)
print(lst)
print(np.log10(lst))

[  10.           31.6227766   100.          316.22776602 1000.        ]
[1.  1.5 2.  2.5 3. ]


In [32]:
#constant abytearray
np.full((4,5),2)

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [33]:
# identity matrix 
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
# between 0 and 1 (uniform)
np.random.random((3,2)) 

array([[0.13054695, 0.43314962],
       [0.2834212 , 0.86295351],
       [0.87500092, 0.81676449]])

In [36]:
# between mean=0 std=1(normal)
np.random.randn(3,2)

array([[ 1.41460911, -2.08820161],
       [-0.87994434, -0.06878267],
       [-0.77177999,  0.263662  ]])

In [39]:
# between loc=mean scale=std(normal)
np.random.normal(loc=1, scale=2, size=(3,2))

array([[ 2.61096756, -0.02623951],
       [ 1.10888163,  1.41048515],
       [ 0.18583152,  0.77690359]])

In [42]:
# copy sort reshape 
arr = np.array([[4,5,6],[1,2,3]]) 
arr_copy = arr.copy() 
arr_copy

arr_copy = arr # do not do 

In [44]:
# sort 
arr1 = np.array([2,3,1,4,5])
arr1.sort()
arr1

array([1, 2, 3, 4, 5])

In [45]:
# flatten rank2 to rank1 
arr2 = np.array([[1,2], [3,4], [5,6], [7,8]])
arr2 

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [46]:
arr2.flatten() #option1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [48]:
arr2.ravel() #option2

array([1, 2, 3, 4, 5, 6, 7, 8])

In [51]:
#transpose 
arr2.T
arr2.transpose()

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [52]:
arr2

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [53]:
# reshape 
arr3 = np.array([[1,2], [3,4], [5,6], [7,8], [9,10], [0,0]])
arr3

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [ 0,  0]])

In [54]:
arr3.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10,  0,  0]])

In [56]:
# add or remove 
arr1

array([1, 2, 3, 4, 5])

In [58]:
np.append(arr1,-12)

array([  1,   2,   3,   4,   5, -12])

In [59]:
np.insert(arr1, 1, 100)

array([  1, 100,   2,   3,   4,   5])

In [60]:
np.delete(arr1, 1, axis=0) #delete 2nd row

array([1, 3, 4, 5])

In [61]:
arr2

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [62]:
np.delete(arr2, 1, axis=0) #delete 2nd row

array([[1, 2],
       [5, 6],
       [7, 8]])

In [63]:
arr2

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [64]:
np.delete(arr2, 1, axis=1) #delete 2nd row

array([[1],
       [3],
       [5],
       [7]])

In [65]:
# combine or split array 
arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[-1,-2,-3], [-4,-5,-6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
np.concatenate((arr1, arr2),axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [-1, -2, -3],
       [-4, -5, -6]])

In [67]:
np.concatenate((arr1, arr2),axis=1)

array([[ 1,  2,  3, -1, -2, -3],
       [ 4,  5,  6, -4, -5, -6]])

In [72]:
# stack 2 array verticallya1
np.vstack((arr1,arr2)) #option1
np.r_[arr1, arr2] #option1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [-1, -2, -3],
       [-4, -5, -6]])

In [73]:
# stack 2 array horizontally
np.hstack((arr1,arr2)) #option1
np.c_[arr1, arr2] #option1

array([[ 1,  2,  3, -1, -2, -3],
       [ 4,  5,  6, -4, -5, -6]])

In [74]:
# split verticalya1
arr3

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [ 0,  0]])

In [75]:
np.vsplit(arr3, 3)

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [ 0,  0]])]

In [79]:
#split horizontally
x = np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [78]:
np.hsplit(x,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [80]:
# index, slice, subset 
x = np.arange(10)

In [81]:
x[2]

np.int64(2)

In [82]:
x.shape = (2,5)

In [83]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [84]:
x[0]

array([0, 1, 2, 3, 4])

In [85]:
x[1,1]

np.int64(6)

In [86]:
x[1,1] = 100

In [89]:
x[1, 2:]

array([7, 8, 9])

In [88]:
# boolean 
x<=3

array([[ True,  True,  True,  True, False],
       [False, False, False, False, False]])

In [91]:
# mask 
y = np.array([1,2,3,4,5,6,7,-10])
y <= 3

y[y<=3]

array([  1,   2,   3, -10])

In [92]:
# scaler math 
arr = np.arange(6).reshape(2,3)

In [93]:
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [104]:
np.add(arr, 1)
np.subtract(arr, 1)
np.multiply(arr, -1)
np.divide(arr, 10)
np.sqrt(arr)
np.sin(arr)
# np.log(arr)
np.abs(arr)
np.log(np.abs(arr))
np.ceil(arr)
np.floor(arr)
np.round(arr)
np.exp(arr)

C:\Users\jewel\AppData\Local\Temp\ipykernel_6204\1207320560.py:9: RuntimeWarning: divide by zero encountered in log
  np.log(np.abs(arr))


array([[  1.        ,   2.71828183,   7.3890561 ],
       [ 20.08553692,  54.59815003, 148.4131591 ]])

In [105]:
# vector math 
arr1 = np.arange(6).reshape(2,3)
arr2 = np.full((2,3),2)
arr1

array([[0, 1, 2],
       [3, 4, 5]])

In [106]:
arr2

array([[2, 2, 2],
       [2, 2, 2]])

In [110]:
np.add(arr1, arr2)
np.subtract(arr1, arr2)
np.multiply(arr1, arr2)
np.divide(arr1, arr2)
np.power(arr1, arr2)
np.array_equal(arr1, arr2)

False

In [3]:
# dot product 
a1 = np.arange(6).reshape(2,3)
a2 = np.arange(6).reshape(3,2)

np.dot(a1, a2)

array([[10, 13],
       [28, 40]])

In [4]:
#statistic

In [12]:
arr = np.array([[0,1,2], [3,4,5]]) # overall mena of all element)
np.mean(arr)
# np.mean(arr, axis=0) # mean for each col 
np.mean(arr, axis=1) # mean for each col 

array([1., 4.])

In [13]:
# cumsum 
print(arr)

[[0 1 2]
 [3 4 5]]


In [15]:
arr.cumsum(axis=1)
arr.cumsum(axis=0)

array([[0, 1, 2],
       [3, 5, 7]])

In [16]:
# correlation coeff 
arr1 = np.linspace(12,50,10)
arr2 = np.random.random(10)
np.corrcoef(arr1, arr2)

array([[1.        , 0.01783818],
       [0.01783818, 1.        ]])

In [17]:
arr1

array([12.        , 16.22222222, 20.44444444, 24.66666667, 28.88888889,
       33.11111111, 37.33333333, 41.55555556, 45.77777778, 50.        ])

In [18]:
arr2

array([0.11561426, 0.31146208, 0.91090304, 0.89950957, 0.78541759,
       0.30517377, 0.94546298, 0.41454371, 0.10707917, 0.62418554])